name: Mythical-Economy
main: com.mythicalgames.economy.EconomyAPI

version: "1.0.0"
api: [ "2.0.0" ]

authors: ["Acktar Badulla", "Mythical Games Team"]
description: An economy plugin with an extensive API to integrate with other plugins supporting both sqlite and mongodb! For powernukkitx
website: https://github.com/Mythical-Games/Mythical-Economy